import localFont from "next/font/local";
import "./globals.css";
import { UIProvider } from "./providers/nextProvider";
import Nav from "./components/navbar/navbar";
import { ReduxProvider } from "./providers/reduxProvider";

import ToasterUI from "./components/toaster/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Travellers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="" lang="en">
      <body
        className={`bg-gradient-to-b from-[#ffffff] w-full   to-[#74DFA2] antialiased`}
      >
        <ReduxProvider>
          <UIProvider>
            <Nav />
            <ToasterUI />
            {children}
          </UIProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
